authorName: drasmuss
experimentName: Keyword Spotter Hyperparam Search
trialConcurrency: 5
maxExecDuration: 1h
trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
logDir: /home/drasmuss/power_benchmarks/data/nni/experiment
#tuner:
#  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
#  #SMAC (SMAC should be installed through nnictl)
#  builtinTunerName: TPE
#  classArgs:
#    optimize_mode: maximize
#assessor:
#  builtinAssessorName: Curvefitting
#  classArgs:
#    optimize_mode: maximize
#    epoch_num: 20
#    threshold: 0.9
advisor:
  builtinAdvisorName: Hyperband
  classArgs:
    R: 20
    eta: 3
    optimize_mode: maximize
trial:
  command: /home/drasmuss/.conda/envs/power_benchmarks/bin/python hyperparam_search.py
  codeDir: ../power_benchmarks
